import '../models/recipe.dart';

class RecipeDatabase {
  static final List<Recipe> initialRecipes = [
    Recipe(
      id: 'rec_chicken_adobo',
      title: 'Classic Chicken & Pork Adobo',
      category: 'Filipino',
      prepTime: '15 min',
      cookTime: '35 min',
      servings: 4,
      calories: '420 kcal',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🍗',
      overview: 'The beloved national dish of the Philippines, featuring chicken braised to fork-tender perfection in soy sauce, vinegar, garlic, and cracked black pepper.',
      nutrition: Nutrition(protein: 38, carbs: 8, fat: 22, fiber: 1),
      chefTips: [
        'Do not stir the vinegar immediately after pouring; let it simmer for 3 minutes to mellow the sharp acidity.',
        'Sear the chicken skin until golden-brown before simmering for deeper savory flavor.',
      ],
      ingredients: [
        Ingredient(name: 'Chicken Thighs & Drumsticks', amount: '800', baseAmount: 800, unit: 'g', category: 'Meat & Seafood'),
        Ingredient(name: 'Soy Sauce', amount: '1/3', baseAmount: 0.33, unit: 'cup', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Cane or White Vinegar', amount: '1/3', baseAmount: 0.33, unit: 'cup', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Garlic', amount: '8', baseAmount: 8, unit: 'cloves', note: 'crushed', category: 'Fresh Produce'),
        Ingredient(name: 'Dried Bay Leaves', amount: '3', baseAmount: 3, unit: 'pcs', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Whole Black Peppercorns', amount: '1', baseAmount: 1, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Brown Sugar', amount: '1', baseAmount: 1, unit: 'tsp', note: 'optional', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Cooking Oil', amount: '1', baseAmount: 1, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Marinate Meat', text: 'In a mixing bowl, combine chicken, soy sauce, and half of the crushed garlic. Let marinate for 15 minutes.', time: '15 min', timerMinutes: 15),
        InstructionStep(step: 2, title: 'Sear Chicken', text: 'Heat oil in a heavy pot over medium-high heat. Brown chicken pieces on all sides for 5 minutes until golden.', time: '5 min', timerMinutes: 5),
        InstructionStep(step: 3, title: 'Simmer with Vinegar', text: 'Pour in remaining garlic, marinade, vinegar, bay leaves, and peppercorns. Bring to a boil uncovered without stirring for 3 minutes.', time: '3 min', timerMinutes: 3),
        InstructionStep(step: 4, title: 'Braise until Tender', text: 'Cover and reduce heat to low. Simmer for 25 minutes until chicken is fork-tender and sauce is rich.', time: '25 min', timerMinutes: 25),
        InstructionStep(step: 5, title: 'Glaze & Serve', text: 'Uncover, stir in brown sugar, and reduce sauce until glossy and thick. Serve hot over steamed jasmine or garlic rice.', time: '2 min', timerMinutes: 2),
      ],
    ),
    Recipe(
      id: 'rec_crispy_sinangag',
      title: 'Golden Crispy Garlic Fried Rice (Sinangag)',
      category: 'Fried Rice',
      prepTime: '5 min',
      cookTime: '10 min',
      servings: 4,
      calories: '280 kcal',
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🍚',
      overview: 'The quintessential Filipino breakfast staple! Day-old jasmine rice wok-tossed with fragrant toasted golden garlic chips and a touch of sea salt.',
      nutrition: Nutrition(protein: 6, carbs: 54, fat: 6, fiber: 2),
      chefTips: [
        'Always use chilled day-old cooked rice so grains separate cleanly without getting mushy.',
        'Start garlic in cold oil over medium-low heat to toast evenly to golden amber without burning.',
      ],
      ingredients: [
        Ingredient(name: 'Day-Old Cooked Rice', amount: '4', baseAmount: 4, unit: 'cups', note: 'chilled & fluffed', category: 'Grains & Bakery'),
        Ingredient(name: 'Garlic', amount: '10', baseAmount: 10, unit: 'cloves', note: 'finely minced', category: 'Fresh Produce'),
        Ingredient(name: 'Cooking Oil', amount: '2', baseAmount: 2, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Salt & Pepper', amount: '1', baseAmount: 1, unit: 'pinch', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Toasted Garlic Chips', amount: '2', baseAmount: 2, unit: 'tbsp', note: 'for garnish', category: 'Pantry, Oils & Spices'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Crisp the Garlic', text: 'Heat oil in a wide wok over medium-low. Add minced garlic and fry gently until golden and crispy (about 3 minutes). Scoop out half for garnish.', time: '3 min', timerMinutes: 3),
        InstructionStep(step: 2, title: 'Toss the Rice', text: 'Increase heat to high. Add fluffed cold rice to the aromatic garlic oil. Stir-fry vigorously, breaking up clumps with a spatula.', time: '4 min', timerMinutes: 4),
        InstructionStep(step: 3, title: 'Season & Serve', text: 'Season with salt and pepper. Toss for 2 more minutes until piping hot and lightly toasted. Top with crunchy garlic chips.', time: '2 min', timerMinutes: 2),
      ],
    ),
    Recipe(
      id: 'rec_garlic_butter_fried_chicken',
      title: 'Crispy Garlic Butter Fried Chicken',
      category: 'Chicken',
      prepTime: '15 min',
      cookTime: '20 min',
      servings: 4,
      calories: '560 kcal',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🍗',
      overview: 'Ultra-crunchy deep-fried chicken tossed in a rich, velvety glaze of melted butter, roasted garlic, and honey.',
      nutrition: Nutrition(protein: 42, carbs: 24, fat: 34, fiber: 1),
      chefTips: [
        'Double-dredge chicken in seasoned cornstarch for glass-like crispy skin that stays crunchy.',
        'Melt butter over low heat before adding garlic to prevent browning bitterness.',
      ],
      ingredients: [
        Ingredient(name: 'Chicken Wings or Thighs', amount: '800', baseAmount: 800, unit: 'g', category: 'Meat & Seafood'),
        Ingredient(name: 'Cornstarch & Flour', amount: '1', baseAmount: 1, unit: 'cup', category: 'Grains & Bakery'),
        Ingredient(name: 'Butter', amount: '3', baseAmount: 3, unit: 'tbsp', category: 'Dairy & Eggs'),
        Ingredient(name: 'Garlic', amount: '6', baseAmount: 6, unit: 'cloves', note: 'minced', category: 'Fresh Produce'),
        Ingredient(name: 'Honey', amount: '1', baseAmount: 1, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Soy Sauce', amount: '1', baseAmount: 1, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Frying Oil', amount: '2', baseAmount: 2, unit: 'cups', category: 'Pantry, Oils & Spices'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Season & Coat', text: 'Season chicken with salt and garlic powder. Dredge thoroughly in cornstarch-flour mixture.', time: '5 min', timerMinutes: 5),
        InstructionStep(step: 2, title: 'Fry until Golden', text: 'Heat oil to 350°F (175°C). Deep-fry chicken in batches for 12-14 minutes until golden-brown and crispy.', time: '14 min', timerMinutes: 14),
        InstructionStep(step: 3, title: 'Make Glaze & Coat', text: 'In a separate pan, melt butter over medium heat. Sauté garlic until fragrant, stir in honey and soy sauce. Toss hot crispy chicken until coated.', time: '3 min', timerMinutes: 3),
      ],
    ),
    Recipe(
      id: 'rec_yang_chow_fried_rice',
      title: 'Yang Chow Wok Fried Rice',
      category: 'Fried Rice',
      prepTime: '10 min',
      cookTime: '10 min',
      servings: 4,
      calories: '390 kcal',
      image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🥡',
      overview: 'Classic Cantonese restaurant-style fried rice loaded with plump shrimp, sweet Chinese sausage, scrambled eggs, and sweet peas.',
      nutrition: Nutrition(protein: 18, carbs: 48, fat: 12, fiber: 3),
      chefTips: [
        'Scramble the eggs quickly in hot oil first and break into small ribbons.',
        'Wok hei (breath of the wok) comes from tossing on the highest heat possible.',
      ],
      ingredients: [
        Ingredient(name: 'Cooked Jasmine Rice', amount: '4', baseAmount: 4, unit: 'cups', note: 'cold', category: 'Grains & Bakery'),
        Ingredient(name: 'Shrimp', amount: '150', baseAmount: 150, unit: 'g', note: 'peeled & deveined', category: 'Meat & Seafood'),
        Ingredient(name: 'Eggs', amount: '2', baseAmount: 2, unit: 'large', category: 'Dairy & Eggs'),
        Ingredient(name: 'Sweet Peas & Carrots', amount: '1/2', baseAmount: 0.5, unit: 'cup', category: 'Fresh Produce'),
        Ingredient(name: 'Green Onions', amount: '2', baseAmount: 2, unit: 'stalks', note: 'sliced', category: 'Fresh Produce'),
        Ingredient(name: 'Soy Sauce & Sesame Oil', amount: '1.5', baseAmount: 1.5, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Cook Eggs & Protein', text: 'Heat oil in wok. Scramble eggs for 1 minute and set aside. Sauté shrimp and sausage for 2 minutes until pink.', time: '3 min', timerMinutes: 3),
        InstructionStep(step: 2, title: 'Wok-Toss Rice', text: 'Add rice and veggies into the hot wok. Toss vigorously on high heat for 4 minutes with soy sauce and sesame oil.', time: '4 min', timerMinutes: 4),
        InstructionStep(step: 3, title: 'Combine & Serve', text: 'Fold in the cooked eggs, shrimp, and scallions. Toss for 1 more minute and serve steaming hot.', time: '1 min', timerMinutes: 1),
      ],
    ),
    Recipe(
      id: 'rec_chicken_inasal',
      title: 'Bacolod Chicken Inasal',
      category: 'Filipino',
      prepTime: '20 min',
      cookTime: '25 min',
      servings: 4,
      calories: '490 kcal',
      image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🍗',
      overview: 'Famous grilled chicken from Bacolod marinated in calamansi, lemongrass, ginger, garlic, and basted with aromatic achiote chicken oil.',
      nutrition: Nutrition(protein: 44, carbs: 6, fat: 28, fiber: 1),
      chefTips: [
        'Baste liberally with annatto (achuete) garlic oil during the last 5 minutes of grilling for stunning orange color.',
        'Serve with sinangag garlic rice and spiced coconut vinegar dipping sauce.',
      ],
      ingredients: [
        Ingredient(name: 'Chicken Quarters', amount: '1', baseAmount: 1, unit: 'kg', category: 'Meat & Seafood'),
        Ingredient(name: 'Lemongrass', amount: '2', baseAmount: 2, unit: 'stalks', note: 'bruised', category: 'Fresh Produce'),
        Ingredient(name: 'Calamansi or Lime Juice', amount: '3', baseAmount: 3, unit: 'tbsp', category: 'Fresh Produce'),
        Ingredient(name: 'Garlic & Ginger', amount: '2', baseAmount: 2, unit: 'tbsp', note: 'minced', category: 'Fresh Produce'),
        Ingredient(name: 'Annatto (Achuete) Oil', amount: '3', baseAmount: 3, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Brown Sugar & Salt', amount: '1', baseAmount: 1, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Marinate Chicken', text: 'Combine lemongrass, calamansi, garlic, ginger, vinegar, and seasonings. Rub all over chicken and marinate for at least 30 minutes.', time: '30 min', timerMinutes: 30),
        InstructionStep(step: 2, title: 'Grill or Roast', text: 'Grill over medium charcoal or bake in oven at 400°F (200°C) for 20 minutes, turning once.', time: '20 min', timerMinutes: 20),
        InstructionStep(step: 3, title: 'Baste with Achuete Oil', text: 'Brush generously with annatto garlic oil and grill 5 more minutes until skin is charred and fragrant.', time: '5 min', timerMinutes: 5),
      ],
    ),
    Recipe(
      id: 'rec_chicken_arroz_caldo',
      title: 'Chicken Arroz Caldo (Ginger Rice Porridge)',
      category: 'Chicken',
      prepTime: '10 min',
      cookTime: '30 min',
      servings: 4,
      calories: '320 kcal',
      image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🥣',
      overview: 'Comforting Filipino chicken rice porridge infused with generous ginger, toasted garlic, scallions, and hard-boiled eggs.',
      nutrition: Nutrition(protein: 26, carbs: 38, fat: 8, fiber: 2),
      chefTips: [
        'Sauté plenty of fresh julienned ginger in oil first — it gives the broth its healing comfort and warmth.',
        'Drizzle with calamansi and top with golden toasted garlic right before eating.',
      ],
      ingredients: [
        Ingredient(name: 'Chicken Thighs', amount: '500', baseAmount: 500, unit: 'g', note: 'cut into bite pieces', category: 'Meat & Seafood'),
        Ingredient(name: 'Jasmine or Glutinous Rice', amount: '1', baseAmount: 1, unit: 'cup', category: 'Grains & Bakery'),
        Ingredient(name: 'Fresh Ginger', amount: '3', baseAmount: 3, unit: 'tbsp', note: 'julienned', category: 'Fresh Produce'),
        Ingredient(name: 'Garlic & Onion', amount: '1', baseAmount: 1, unit: 'ea', category: 'Fresh Produce'),
        Ingredient(name: 'Chicken Broth', amount: '5', baseAmount: 5, unit: 'cups', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Fish Sauce (Patis)', amount: '2', baseAmount: 2, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Hard Boiled Eggs', amount: '2', baseAmount: 2, unit: 'pcs', category: 'Dairy & Eggs'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Sauté Aromatics', text: 'In a pot, heat oil and sauté ginger, garlic, and onion until deeply fragrant (3 minutes).', time: '3 min', timerMinutes: 3),
        InstructionStep(step: 2, title: 'Brown Chicken', text: 'Add chicken pieces and fish sauce. Cook for 5 minutes until chicken turns white.', time: '5 min', timerMinutes: 5),
        InstructionStep(step: 3, title: 'Simmer Rice Porridge', text: 'Add rice and chicken broth. Bring to a boil, then simmer covered over low heat for 25 minutes, stirring occasionally until thick and creamy.', time: '25 min', timerMinutes: 25),
        InstructionStep(step: 4, title: 'Garnish & Serve', text: 'Ladle into bowls. Top with sliced hard-boiled eggs, scallions, toasted garlic, and calamansi.', time: '2 min', timerMinutes: 2),
      ],
    ),
    Recipe(
      id: 'rec_tuscan_chicken',
      title: 'Creamy Tuscan Garlic Chicken',
      category: 'Chicken',
      prepTime: '10 min',
      cookTime: '20 min',
      servings: 4,
      calories: '520 kcal',
      image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🥘',
      overview: 'Golden pan-seared chicken cutlets bathed in a luscious garlic parmesan cream sauce loaded with sun-dried tomatoes and baby spinach.',
      nutrition: Nutrition(protein: 46, carbs: 9, fat: 32, fiber: 3),
      chefTips: [
        'Use oil from the sun-dried tomato jar to sear the chicken for extra gourmet flavor.',
      ],
      ingredients: [
        Ingredient(name: 'Chicken Breasts', amount: '600', baseAmount: 600, unit: 'g', note: 'cutlets', category: 'Meat & Seafood'),
        Ingredient(name: 'Heavy Cream', amount: '1', baseAmount: 1, unit: 'cup', category: 'Dairy & Eggs'),
        Ingredient(name: 'Sun-Dried Tomatoes', amount: '1/2', baseAmount: 0.5, unit: 'cup', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Baby Spinach', amount: '2', baseAmount: 2, unit: 'cups', category: 'Fresh Produce'),
        Ingredient(name: 'Parmesan Cheese', amount: '1/2', baseAmount: 0.5, unit: 'cup', note: 'grated', category: 'Dairy & Eggs'),
        Ingredient(name: 'Garlic', amount: '4', baseAmount: 4, unit: 'cloves', note: 'minced', category: 'Fresh Produce'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Sear Chicken', text: 'Pan-sear seasoned chicken in olive oil over medium-high heat for 5 minutes per side until golden. Remove and set aside.', time: '10 min', timerMinutes: 10),
        InstructionStep(step: 2, title: 'Build Cream Sauce', text: 'In the same pan, sauté garlic and sun-dried tomatoes. Pour in heavy cream and chicken broth; simmer for 3 minutes.', time: '3 min', timerMinutes: 3),
        InstructionStep(step: 3, title: 'Melt Cheese & Wilt Greens', text: 'Stir in parmesan cheese and baby spinach until wilted and sauce is velvety.', time: '3 min', timerMinutes: 3),
        InstructionStep(step: 4, title: 'Combine & Serve', text: 'Return chicken to pan, spoon sauce over top, and serve immediately with pasta or rice.', time: '2 min', timerMinutes: 2),
      ],
    ),

    // =============================================
    // AUTHENTIC FILIPINO & HALAL SPECIALTIES
    // =============================================
    Recipe(
      id: 'rec_halal_piaparan_manok',
      title: 'Halal Piaparan a Manok (Maranao Coconut Chicken)',
      category: 'Filipino',
      prepTime: '15 min',
      cookTime: '30 min',
      servings: 4,
      calories: '480 kcal',
      image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🍗',
      overview: 'A celebrated Maranao Muslim-Filipino royal specialty. Halal chicken simmered in rich coconut milk infused with fresh turmeric, lemongrass, and fiery ginger Palapa.',
      nutrition: Nutrition(protein: 40, carbs: 12, fat: 28, fiber: 3),
      chefTips: [
        'Palapa is made by pounding scallions, fresh ginger, and bird\'s eye chilies for its signature zesty aroma.',
      ],
      ingredients: [
        Ingredient(name: 'Halal Chicken Cuts', amount: '1', baseAmount: 1, unit: 'kg', category: 'Meat & Seafood'),
        Ingredient(name: 'Pure Coconut Milk (Gata)', amount: '2', baseAmount: 2, unit: 'cups', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Grated Coconut Pulp', amount: '1.5', baseAmount: 1.5, unit: 'cups', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Palapa (Scallions, Ginger, Chili)', amount: '4', baseAmount: 4, unit: 'tbsp', category: 'Fresh Produce'),
        Ingredient(name: 'Fresh Turmeric Powder', amount: '1', baseAmount: 1, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Lemongrass (Tanglad)', amount: '2', baseAmount: 2, unit: 'stalks', category: 'Fresh Produce'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Simmer Chicken', text: 'Combine chicken, lemongrass, turmeric, half the Palapa, salt, and water. Simmer 15 min until tender.', time: '15 min', timerMinutes: 15),
        InstructionStep(step: 2, title: 'Add Coconut Cream', text: 'Pour in coconut milk and chilies. Simmer gently for 10 minutes until golden.', time: '10 min', timerMinutes: 10),
        InstructionStep(step: 3, title: 'Toast Coconut Topping', text: 'Toast grated coconut pulp with turmeric and Palapa for 5 min until crispy.', time: '5 min', timerMinutes: 5),
        InstructionStep(step: 4, title: 'Assemble & Crown', text: 'Ladle chicken and sauce into bowls. Top with toasted spiced coconut. Serve with jasmine rice.', time: '2 min', timerMinutes: 2),
      ],
    ),
    Recipe(
      id: 'rec_halal_chicken_inasal',
      title: 'Halal Bacolod Grilled Chicken Inasal',
      category: 'Filipino',
      prepTime: '20 min',
      cookTime: '25 min',
      servings: 4,
      calories: '450 kcal',
      image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🍗',
      overview: 'Famous Western Visayas grilled chicken marinated in lemongrass, calamansi, ginger, garlic, and coconut vinegar, basted with golden aromatic achuete oil.',
      nutrition: Nutrition(protein: 46, carbs: 6, fat: 24, fiber: 1),
      chefTips: [
        'Basting with warm annatto-garlic butter creates that iconic amber-red gloss unique to authentic Bacolod Inasal.',
      ],
      ingredients: [
        Ingredient(name: 'Halal Chicken Leg Quarters', amount: '4', baseAmount: 4, unit: 'pcs', category: 'Meat & Seafood'),
        Ingredient(name: 'Calamansi / Lime Juice', amount: '1/4', baseAmount: 0.25, unit: 'cup', category: 'Fresh Produce'),
        Ingredient(name: 'Coconut Vinegar', amount: '1/2', baseAmount: 0.5, unit: 'cup', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Lemongrass', amount: '3', baseAmount: 3, unit: 'stalks', category: 'Fresh Produce'),
        Ingredient(name: 'Garlic & Ginger', amount: '8 cloves + 2 tbsp', baseAmount: 8, unit: '', category: 'Fresh Produce'),
        Ingredient(name: 'Achuete Oil & Butter', amount: '4', baseAmount: 4, unit: 'tbsp each', category: 'Pantry, Oils & Spices'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Marinate Chicken', text: 'Whisk calamansi, vinegar, lemongrass, garlic, ginger, sugar, and salt. Rub over chicken and marinate 30 min.', time: '30 min', timerMinutes: 30),
        InstructionStep(step: 2, title: 'Prepare Basting Oil', text: 'Warm butter with achuete oil and salt until fragrant and vibrant orange.', time: '3 min', timerMinutes: 3),
        InstructionStep(step: 3, title: 'Grill with Basting', text: 'Grill chicken 10-12 min per side, brushing with annatto butter every 3 min until charred and cooked.', time: '22 min', timerMinutes: 22),
        InstructionStep(step: 4, title: 'Serve with Sinangag', text: 'Serve hot with garlic rice, calamansi-soy-chili dip, and extra chicken oil drizzled on top.', time: '2 min', timerMinutes: 2),
      ],
    ),
    Recipe(
      id: 'rec_halal_beef_kulma',
      title: 'Halal Tausug Beef Kulma (Curry Peanut Stew)',
      category: 'Filipino',
      prepTime: '15 min',
      cookTime: '40 min',
      servings: 4,
      calories: '540 kcal',
      image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🥩',
      overview: 'A luxurious Mindanao Muslim-Filipino festive stew. Tender halal beef cooked with coconut milk, peanut butter, curry spices, and tomato sauce.',
      nutrition: Nutrition(protein: 42, carbs: 16, fat: 34, fiber: 3),
      chefTips: [
        'Beef Kulma is the harmonious blend between Filipino Mechado and South Asian Korma — rich and deeply comforting.',
      ],
      ingredients: [
        Ingredient(name: 'Halal Beef Chuck / Shank', amount: '800', baseAmount: 800, unit: 'g', category: 'Meat & Seafood'),
        Ingredient(name: 'Coconut Milk (Gata)', amount: '2', baseAmount: 2, unit: 'cups', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Creamy Peanut Butter', amount: '3', baseAmount: 3, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Tomato Paste or Sauce', amount: '1/2', baseAmount: 0.5, unit: 'cup', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Curry Powder & Paprika', amount: '1.5', baseAmount: 1.5, unit: 'tbsp each', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Garlic, Onion, Ginger, Lemongrass', amount: '5 cloves + aromatics', baseAmount: 1, unit: '', category: 'Fresh Produce'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Marinate Beef', text: 'Toss beef with curry powder, calamansi juice, salt, and pepper. Rest 15 min.', time: '15 min', timerMinutes: 15),
        InstructionStep(step: 2, title: 'Sauté & Brown', text: 'Sauté garlic, onions, ginger. Add beef and sear until browned.', time: '8 min', timerMinutes: 8),
        InstructionStep(step: 3, title: 'Simmer in Gravy', text: 'Add tomato sauce, lemongrass, and water. Simmer 25 min until fork-tender.', time: '25 min', timerMinutes: 25),
        InstructionStep(step: 4, title: 'Add Peanut & Coconut', text: 'Stir in peanut butter and coconut milk. Simmer 8-10 min until thick and velvety.', time: '8 min', timerMinutes: 8),
      ],
    ),
    Recipe(
      id: 'rec_halal_chicken_tinola',
      title: 'Halal Chicken Tinola with Moringa',
      category: 'Filipino',
      prepTime: '10 min',
      cookTime: '25 min',
      servings: 4,
      calories: '340 kcal',
      image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🍲',
      overview: 'Classic comforting Filipino chicken ginger soup with green papaya wedges and nutrient-dense fresh moringa (malunggay) leaves.',
      nutrition: Nutrition(protein: 38, carbs: 10, fat: 14, fiber: 3),
      chefTips: [
        'Lots of fresh ginger is the key to an authentic, warming Tinola broth that soothes and revives.',
      ],
      ingredients: [
        Ingredient(name: 'Halal Chicken Cuts', amount: '800', baseAmount: 800, unit: 'g', category: 'Meat & Seafood'),
        Ingredient(name: 'Fresh Ginger', amount: '3', baseAmount: 3, unit: 'tbsp', note: 'matchsticks', category: 'Fresh Produce'),
        Ingredient(name: 'Garlic & Red Onion', amount: '4 cloves + 1 onion', baseAmount: 1, unit: '', category: 'Fresh Produce'),
        Ingredient(name: 'Green Papaya or Sayote', amount: '1', baseAmount: 1, unit: 'medium', category: 'Fresh Produce'),
        Ingredient(name: 'Moringa / Spinach Leaves', amount: '2', baseAmount: 2, unit: 'cups', category: 'Fresh Produce'),
        Ingredient(name: 'Fish Sauce (Patis)', amount: '2', baseAmount: 2, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Sauté Ginger', text: 'Heat oil, sauté ginger 2 min until fragrant. Add garlic and onion.', time: '3 min', timerMinutes: 3),
        InstructionStep(step: 2, title: 'Sear Chicken', text: 'Add chicken and fish sauce. Cook 5 min until lightly browned.', time: '5 min', timerMinutes: 5),
        InstructionStep(step: 3, title: 'Simmer Broth', text: 'Pour in water/broth. Boil, then simmer 15 min. Add papaya and cook 5 more min.', time: '20 min', timerMinutes: 20),
        InstructionStep(step: 4, title: 'Add Moringa', text: 'Add chilies, turn off heat. Scatter moringa on top, cover 2 min. Serve hot!', time: '2 min', timerMinutes: 2),
      ],
    ),
    Recipe(
      id: 'rec_halal_fish_escabeche',
      title: 'Halal Sweet & Sour Fish Escabeche',
      category: 'Filipino',
      prepTime: '10 min',
      cookTime: '15 min',
      servings: 4,
      calories: '380 kcal',
      image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80',
      imageIcon: '🐟',
      overview: 'Crispy pan-fried whole fish blanketed with colorful bell peppers, onions, carrots, and a glossy sweet-tangy ginger escabeche glaze.',
      nutrition: Nutrition(protein: 34, carbs: 22, fat: 15, fiber: 2),
      chefTips: [
        'Pat fish completely dry before frying so the skin crisps into a golden crust.',
      ],
      ingredients: [
        Ingredient(name: 'Whole Fish (Snapper/Tilapia)', amount: '1', baseAmount: 1, unit: 'large', category: 'Meat & Seafood'),
        Ingredient(name: 'Bell Peppers (Red & Green)', amount: '1', baseAmount: 1, unit: 'each', category: 'Fresh Produce'),
        Ingredient(name: 'Carrot & Ginger', amount: '1 + 2 tbsp', baseAmount: 1, unit: '', note: 'julienned', category: 'Fresh Produce'),
        Ingredient(name: 'Cane Vinegar', amount: '1/3', baseAmount: 0.33, unit: 'cup', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Brown Sugar', amount: '3', baseAmount: 3, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
        Ingredient(name: 'Tomato Sauce / Ketchup', amount: '3', baseAmount: 3, unit: 'tbsp', category: 'Pantry, Oils & Spices'),
      ],
      instructions: [
        InstructionStep(step: 1, title: 'Crisp Fry Fish', text: 'Season fish with salt. Fry 5-6 min per side until golden and crunchy.', time: '12 min', timerMinutes: 12),
        InstructionStep(step: 2, title: 'Sauté Vegetables', text: 'Sauté ginger, garlic, onion, carrots, and bell peppers 3 min until crisp-tender.', time: '3 min', timerMinutes: 3),
        InstructionStep(step: 3, title: 'Make Sweet & Sour Sauce', text: 'Add vinegar, sugar, tomato sauce, water. Boil, add cornstarch slurry until thick.', time: '3 min', timerMinutes: 3),
        InstructionStep(step: 4, title: 'Glaze & Serve', text: 'Pour piping hot sweet-sour vegetable sauce over the crispy fish. Serve with rice.', time: '1 min', timerMinutes: 1),
      ],
    ),
  ];
}
